name: QEMU Build

on: push

env:
  QEMU_IMAGE: tonistiigi/binfmt:qemu-v5.0.1

jobs:
  qemu_platform_info:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up QEMU for all platforms
        id: qemu
        uses: docker/setup-qemu-action@v1
        with:
          image: ${{ env.QEMU_IMAGE }}
          platforms: all
      -
        name: Available platforms
        run: echo ${{ steps.qemu.outputs.platforms }}

  # https://github.com/midwan/amiberry/wiki/Available-Platforms
  qemu_build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
#          - platform: linux/arm/v7
#            make_platform: rpi4
#            extra_debs: libraspberrypi-dev libraspberrypi0
          - platform: linux/arm/v7
            make_platform: rpi4-sdl2
          - platform: linux/arm/v7
            make_platform: rpi3-sdl2
          - platform: linux/arm/v7
            make_platform: rpi2-sdl2
          #- platform: linux/arm/v7
          #  make_platform: rpi1-sdl2
          - platform: linux/arm64
            make_platform: rpi4-64-sdl2
          - platform: linux/arm64
            make_platform: rpi3-64-sdl2
          - platform: linux/arm/v7
            make_platform: orangepi-pc
          - platform: linux/arm/v7
            make_platform: xu4
          - platform: linux/arm/v7
            make_platform: c1
          - platform: linux/arm64
            make_platform: n2
          - platform: linux/arm/v7
            make_platform: vero4k
          - platform: linux/arm/v7
            make_platform: AMLGXBB
          - platform: linux/arm/v7
            make_platform: AMLGXL
          - platform: linux/arm/v7
            make_platform: AMLGXM
          - platform: linux/arm/v7
            make_platform: AMLG12A
          - platform: linux/arm/v7
            make_platform: AMLG12B
          #- platform: linux/arm/v7
          #  make_platform: AMLSM1
          - platform: linux/arm64
            make_platform: oga
          - platform: linux/arm64
            make_platform: a64
          - platform: linux/arm/v7
            make_platform: RK3288
          - platform: linux/arm/v7
            make_platform: RK3328
          - platform: linux/arm/v7
            make_platform: RK3399
          - platform: linux/arm/v7
            make_platform: RK3326
          - platform: linux/arm/v7
            make_platform: sun8i
          - platform: linux/arm64
            make_platform: lePotato
          - platform: linux/arm64
            make_platform: jetson-nano
          - platform: linux/arm64
            make_platform: mali-drm-gles-sdl2
          - platform: linux/arm/v7
            make_platform: s812
          - platform: linux/amd64
            make_platform: x86-64

    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up QEMU for ${{ matrix.platform }}
        id: qemu
        uses: docker/setup-qemu-action@v1
        with:
          image: ${{ env.QEMU_IMAGE }}
          platforms: ${{ matrix.platform }}
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1        
      -
        name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      -
        name: Copy Dockerfile
        run: |
          cp .github/workflows/Dockerfile .

      -
        name: Build on ${{ matrix.platform }}
        uses: docker/build-push-action@v2
        with:
          context: .
          platforms: ${{ matrix.platform }}
          build-args: |
            PLATFORM=${{ matrix.make_platform }}
            EXTRA_DEBS=${{ matrix.extra_debs }}
          outputs: "type=tar,dest=image.tar"
      -
        name: Show it
        run: |
          ls -alR image.tar
          tar -tvf image.tar
          
      -
        name: Extract executable
        run: |
          tar --wildcards -xvf image.tar build/amiberry
          cp build/amiberry amiberry_${{ matrix.make_platform }}

      - uses: actions/upload-artifact@v2
        with:
          name: amiberry_${{ matrix.make_platform }}
          path: amiberry_${{ matrix.make_platform }}

      - uses: actions/upload-artifact@v2
        with:
          name: amiberry_all
          path: amiberry_${{ matrix.make_platform }}