name: QEMU Build

on: push

env:
  QEMU_IMAGE: tonistiigi/binfmt:qemu-v5.0.1

jobs:
  qemu_platform_info:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up QEMU for all platforms
        id: qemu
        uses: docker/setup-qemu-action@v1
        with:
          image: ${{ env.QEMU_IMAGE }}
          platforms: all
      -
        name: Available platforms
        run: echo ${{ steps.qemu.outputs.platforms }}

  # https://github.com/midwan/amiberry/wiki/Available-Platforms
  qemu_build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - platform: linux/arm/v7
            make_platform: rpi2-sdl2

    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up QEMU for ${{ matrix.platform }}
        id: qemu
        uses: docker/setup-qemu-action@v1
        with:
          image: ${{ env.QEMU_IMAGE }}
          platforms: ${{ matrix.platform }}
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1        
      -
        name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      -
        name: Copy Dockerfile
        run: |
          cp .github/workflows/Dockerfile .

      -
        name: Build on ${{ matrix.platform }}
        uses: docker/build-push-action@v2
        with:
          context: .
          platforms: ${{ matrix.platform }}
          build-args: |
            PLATFORM=${{ matrix.make_platform }}
            EXTRA_DEBS=${{ matrix.extra_debs }}
          outputs: "type=tar,dest=image.tar"
      -
        name: Show it
        run: |
          ls -alR image.tar
          tar -tvf image.tar
          
      -
        name: Extract executable
        run: |
          tar --wildcards -xvf image.tar build/amiberry
          cp build/amiberry amiberry_${{ matrix.make_platform }}

      - uses: actions/upload-artifact@v2
        with:
          name: amiberry_${{ matrix.make_platform }}
          path: amiberry_${{ matrix.make_platform }}

      - uses: actions/upload-artifact@v2
        with:
          name: amiberry_all
          path: amiberry_${{ matrix.make_platform }}
